services:
  - type: web
    name: pstslove2
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 3000
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
